-- ============================================================
-- Extend dish_catalog with nutrition data (macros + micros + spices
-- + benefits + cooking tip). Additive only — never touches the
-- cook-engine columns (name_hi, image_url, is_fallback, fallback_priority).
--
-- Discrete macro columns (not JSONB) so member/guest consumption can be
-- SQL-aggregated; micros/whole_spices/benefits stay JSONB since they're
-- display-only variable-shape data.
-- ============================================================

ALTER TABLE dish_catalog
  ADD COLUMN IF NOT EXISTS serving_size         TEXT,
  ADD COLUMN IF NOT EXISTS calories             NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS protein_g            NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS carbs_g              NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS fats_g               NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS fiber_g              NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS micros               JSONB,   -- [{name,value,unit,rdv,benefit,color}]
  ADD COLUMN IF NOT EXISTS whole_spices         JSONB,   -- ["cumin seeds (jeera)", ...]
  ADD COLUMN IF NOT EXISTS benefits             JSONB,   -- ["...", ...]
  ADD COLUMN IF NOT EXISTS cooking_tip          TEXT,
  ADD COLUMN IF NOT EXISTS nutrition_status     TEXT NOT NULL DEFAULT 'none'
    CHECK (nutrition_status IN ('none', 'estimated', 'approved')),
  ADD COLUMN IF NOT EXISTS nutrition_updated_at TIMESTAMPTZ;

-- Existing RLS on dish_catalog (anyone_read, admins_write from 20260706)
-- already covers these new columns — no policy changes needed.

-- ── Seed: the 12 curated dishes previously hardcoded in
-- apps/web/src/app/food-hub/nutrition/page.tsx (INITIAL_DISHES). Extracted
-- programmatically from that source to avoid transcription errors. These
-- become the initial approved dish library once the page reads from
-- dish_catalog instead of localStorage (Phase 5).
INSERT INTO dish_catalog (
  name, name_hi, image_url, is_fallback, fallback_priority, active,
  serving_size, calories, protein_g, carbs_g, fats_g, fiber_g,
  micros, whole_spices, benefits, cooking_tip, nutrition_status, nutrition_updated_at
) VALUES
  ('Moong Dal Cheela', NULL, NULL, false, 0, true, '2 medium cheelas', 185, 12, 25, 4, 5, '[{"name":"Iron","value":2.5,"unit":"mg","rdv":18,"benefit":"Red blood cell formation","color":"#D67D61"},{"name":"Folate","value":125,"unit":"mcg","rdv":400,"benefit":"DNA synthesis & cell growth","color":"#8BA88E"},{"name":"Magnesium","value":48,"unit":"mg","rdv":420,"benefit":"Muscle & nerve function","color":"#A8C5DA"},{"name":"Zinc","value":1.5,"unit":"mg","rdv":11,"benefit":"Immune defense","color":"#C4A882"}]'::jsonb, '["Cumin seeds (jeera)","Black pepper","Turmeric (haldi)","Green chili","Fresh coriander"]'::jsonb, '["High plant protein","Low glycemic index — sustained energy","Folate-rich for cellular health","Naturally gluten-free"]'::jsonb, 'Soak dal 4 hours for better digestibility. Cook on medium heat with ½ tsp ghee. Squeeze lemon after cooking — Vitamin C boosts iron absorption.', 'approved', NOW()),
  ('Palak Dal', NULL, NULL, false, 0, true, '1 katori (200ml)', 195, 13, 28, 4, 7, '[{"name":"Iron","value":5.2,"unit":"mg","rdv":18,"benefit":"Prevents anaemia — top plant source","color":"#D67D61"},{"name":"Vitamin A","value":580,"unit":"mcg","rdv":900,"benefit":"Eye health & immunity","color":"#F5C842"},{"name":"Calcium","value":180,"unit":"mg","rdv":1000,"benefit":"Bone density","color":"#A8C5DA"},{"name":"Vitamin K","value":145,"unit":"mcg","rdv":120,"benefit":"Blood clotting & bone metabolism","color":"#C4A882"}]'::jsonb, '["Mustard seeds (rai)","Cumin seeds","Dried red chili","Asafoetida (hing)","Turmeric"]'::jsonb, '["Iron + Vitamin C synergy maximises absorption","All 13 essential vitamins","Dal + rice = complete protein","Beta-carotene precursor of Vitamin A"]'::jsonb, 'Use 1 tsp ghee for tadka — enhances fat-soluble vitamin absorption. Always squeeze lemon at end: Vitamin C triples iron absorption from plant sources.', 'approved', NOW()),
  ('Ragi Idli', NULL, NULL, false, 0, true, '3 idlis (150g)', 168, 7, 32, 2, 4.5, '[{"name":"Calcium","value":244,"unit":"mg","rdv":1000,"benefit":"Strongest plant calcium source","color":"#A8C5DA"},{"name":"Iron","value":3.6,"unit":"mg","rdv":18,"benefit":"Oxygen transport","color":"#D67D61"},{"name":"Phosphorus","value":280,"unit":"mg","rdv":700,"benefit":"Bone formation & energy storage","color":"#C4A882"}]'::jsonb, '["Fenugreek seeds in batter (methi)","Curry leaves in sambar","Mustard seeds","Cumin","Asafoetida"]'::jsonb, '["Highest calcium among Indian grains — rivals dairy","Naturally gluten-free","Low glycemic index (GI 40)","Fermentation enhances B12 bioavailability"]'::jsonb, 'Add ½ tsp fenugreek seeds while soaking urad dal — improves fermentation and adds iron. Ferment 10–12 hours for maximum probiotic benefit.', 'approved', NOW()),
  ('Rajma (Kidney Beans)', NULL, NULL, false, 0, true, '1 cup cooked (200g)', 225, 15, 40, 1, 11, '[{"name":"Iron","value":5,"unit":"mg","rdv":18,"benefit":"Top plant iron source","color":"#D67D61"},{"name":"Potassium","value":742,"unit":"mg","rdv":4700,"benefit":"Heart health & blood pressure","color":"#F5C842"},{"name":"Folate","value":230,"unit":"mcg","rdv":400,"benefit":"DNA synthesis","color":"#8BA88E"},{"name":"Magnesium","value":74,"unit":"mg","rdv":420,"benefit":"Blood glucose regulation","color":"#A8C5DA"}]'::jsonb, '["Bay leaf","Cinnamon","Cloves","Black cardamom","Cumin seeds","Freshly crushed coriander","Turmeric"]'::jsonb, '["11g fiber per serving","Resistant starch feeds gut bacteria","Low glycemic index (GI 24)","Complete protein with rice"]'::jsonb, 'Soak overnight 12h — reduces flatulence oligosaccharides by 60%. Use 1 tsp oil. Tomato base provides natural Vitamin C to boost iron absorption.', 'approved', NOW()),
  ('Mushroom Palak Masala', NULL, NULL, false, 0, true, '1 cup (200g)', 120, 8, 12, 5, 4, '[{"name":"Vitamin D","value":5,"unit":"mcg","rdv":20,"benefit":"Bone health & immune regulation","color":"#F5C842"},{"name":"Selenium","value":25,"unit":"mcg","rdv":55,"benefit":"Thyroid & antioxidant defense","color":"#C4A882"},{"name":"Iron","value":3.5,"unit":"mg","rdv":18,"benefit":"Oxygen transport","color":"#D67D61"},{"name":"Vitamin K","value":108,"unit":"mcg","rdv":120,"benefit":"Blood clotting & bone metabolism","color":"#8BA88E"}]'::jsonb, '["Cumin seeds","Freshly crushed coriander seeds","Green cardamom","Black pepper","Turmeric","Bay leaf"]'::jsonb, '["Mushrooms: one of few plant sources of Vitamin D","Selenium supports thyroid health","Beta-glucans modulate immune response","Near-zero cholesterol"]'::jsonb, 'Expose mushrooms to sunlight 1 hour before cooking — doubles Vitamin D. Use 1 tsp oil; mushrooms release their own moisture.', 'approved', NOW()),
  ('Vegetable Khichdi', NULL, NULL, false, 0, true, '1 bowl (300g)', 285, 12, 48, 6, 6, '[{"name":"Zinc","value":2.2,"unit":"mg","rdv":11,"benefit":"Immune defense & wound healing","color":"#C4A882"},{"name":"Magnesium","value":60,"unit":"mg","rdv":420,"benefit":"Relaxation & sleep quality","color":"#A8C5DA"},{"name":"Lysine","value":0.8,"unit":"g","rdv":2.1,"benefit":"Complete protein via rice+dal synergy","color":"#8BA88E"}]'::jsonb, '["Cumin seeds","Bay leaf","Turmeric","Black peppercorns (2–3)","Fresh ginger"]'::jsonb, '["Easiest to digest — ideal for dinner","Complete protein: rice + dal synergy","Magnesium promotes muscle relaxation & sleep","Ayurvedic gut restoration staple"]'::jsonb, 'Use 1 part moong dal : 1 part brown rice. The 1 tsp ghee tadka is essential — provides butyrate for gut lining healing.', 'approved', NOW()),
  ('Oats Vegetable Upma', NULL, NULL, false, 0, true, '1 bowl (250g)', 225, 7, 36, 6, 5, '[{"name":"Beta-glucan","value":2,"unit":"g","rdv":3,"benefit":"FDA-approved cholesterol lowering","color":"#8BA88E"},{"name":"Vitamin B1","value":0.4,"unit":"mg","rdv":1.2,"benefit":"Carbohydrate metabolism","color":"#F5C842"},{"name":"Magnesium","value":52,"unit":"mg","rdv":420,"benefit":"Energy production & bone health","color":"#A8C5DA"}]'::jsonb, '["Mustard seeds","Cumin seeds","Curry leaves","Dried red chili","Fresh ginger","Turmeric"]'::jsonb, '["Beta-glucan: only food fiber with FDA cholesterol-lowering claim","Sustained energy 4–5 hours","Avenanthramide antioxidants unique to oats","Feeds Bifidobacterium probiotic bacteria"]'::jsonb, 'Use steel-cut oats (lower GI: 55 vs 79 for instant). Add 1 tbsp roasted peanuts for protein. Use 1 tsp coconut oil — MCTs support brain health.', 'approved', NOW()),
  ('Quinoa Vegetable Pulao', NULL, NULL, false, 0, true, '1 cup cooked (200g)', 220, 8, 39, 4, 4, '[{"name":"Complete Protein","value":4.4,"unit":"g EAA","rdv":8,"benefit":"All 9 essential amino acids in one grain","color":"#8BA88E"},{"name":"Magnesium","value":118,"unit":"mg","rdv":420,"benefit":"Highest among grains — 300+ reactions","color":"#A8C5DA"},{"name":"Iron","value":2.8,"unit":"mg","rdv":18,"benefit":"Pair with Vitamin C for best absorption","color":"#D67D61"}]'::jsonb, '["Bay leaf","Green cardamom (2)","Cloves (2)","Cinnamon","Cumin seeds","Black pepper","Star anise (1)"]'::jsonb, '["One of very few complete plant proteins","Magnesium 4× higher than white rice","Gluten-free with high satiety","Flavonoid quercetin rivals vegetables"]'::jsonb, 'Rinse quinoa thoroughly to remove saponins. Toast dry before cooking for nutty flavor. Use vegetable stock instead of water.', 'approved', NOW()),
  ('Kala Chana Masala', NULL, NULL, false, 0, true, '1 cup cooked (200g)', 210, 14, 35, 2, 10, '[{"name":"Iron","value":6,"unit":"mg","rdv":18,"benefit":"Highest iron among chickpeas","color":"#D67D61"},{"name":"Phosphorus","value":380,"unit":"mg","rdv":700,"benefit":"Bone mineralization","color":"#C4A882"},{"name":"Zinc","value":3,"unit":"mg","rdv":11,"benefit":"Strong immune cells & skin repair","color":"#8BA88E"},{"name":"Potassium","value":620,"unit":"mg","rdv":4700,"benefit":"Blood pressure regulation","color":"#F5C842"}]'::jsonb, '["Anardana (dried pomegranate)","Cumin seeds","Freshly crushed coriander","Black cardamom","Bay leaf","Cinnamon","Turmeric"]'::jsonb, '["Dark pigment = higher antioxidants","10g fiber feeds gut microbiome","Resistant starch (GI 28)","Iron + zinc combo for energy and immunity"]'::jsonb, 'Soak overnight. Slow cook — caramelises natural sugars for rich flavour without masala powder. Anardana adds Vitamin C naturally.', 'approved', NOW()),
  ('Sprouted Moong Chaat', NULL, NULL, false, 0, true, '1 bowl (100g)', 140, 8, 22, 2, 6, '[{"name":"Vitamin C","value":22,"unit":"mg","rdv":90,"benefit":"Immune boost & iron absorption","color":"#F5C842"},{"name":"Iron","value":2.2,"unit":"mg","rdv":18,"benefit":"Haemoglobin synthesis","color":"#D67D61"},{"name":"Folate","value":80,"unit":"mcg","rdv":400,"benefit":"Cell division & growth","color":"#8BA88E"}]'::jsonb, '["Roasted cumin (freshly ground)","Black salt (kala namak)","Fresh coriander","Green chili","Lemon juice"]'::jsonb, '["Sprouting doubles Vitamin C content","Live enzymes aid protein digestion","Anti-inflammatory isoflavones","Raw = maximum micronutrient retention"]'::jsonb, 'No cooking needed — preserves all enzymes and heat-sensitive vitamins. Top with pomegranate, cucumber, and lime.', 'approved', NOW()),
  ('Set Dosa + Sambar', NULL, NULL, false, 0, true, '2 dosas + 1 katori sambar', 320, 10, 56, 6, 4, '[{"name":"Probiotics","value":1,"unit":"billion CFU","rdv":1,"benefit":"Gut microbiome diversity","color":"#8BA88E"},{"name":"Iron","value":3.2,"unit":"mg","rdv":18,"benefit":"From dal in sambar","color":"#D67D61"},{"name":"Vitamin C","value":15,"unit":"mg","rdv":90,"benefit":"From tomatoes in sambar","color":"#F5C842"}]'::jsonb, '["Mustard seeds","Curry leaves","Dried red chili","Asafoetida (hing)","Turmeric","Cumin seeds"]'::jsonb, '["Fermentation increases nutrient bioavailability","Lactic acid bacteria improve gut flora","Rice + Urad dal = synergistic amino acids","Probiotic support for immunity"]'::jsonb, 'Ferment batter 12–16 hours for maximum probiotic activity. Add drumstick (moringa) to sambar — 7× more Vitamin C than oranges.', 'approved', NOW()),
  ('Besan Cheela', NULL, NULL, false, 0, true, '2 medium cheelas', 165, 10, 20, 6, 4, '[{"name":"Folate","value":140,"unit":"mcg","rdv":400,"benefit":"DNA synthesis & neural health","color":"#8BA88E"},{"name":"Iron","value":2,"unit":"mg","rdv":18,"benefit":"Oxygen carrying capacity","color":"#D67D61"},{"name":"Vitamin B6","value":0.2,"unit":"mg","rdv":1.7,"benefit":"Mood regulation (serotonin synthesis)","color":"#F5C842"}]'::jsonb, '["Cumin seeds","Turmeric","Freshly ground coriander","Black pepper","Fresh ginger"]'::jsonb, '["Chickpea flour = excellent plant protein + folate","Gluten-free","B6 supports neurotransmitter production","Stuffed with veg = minimal extra calories"]'::jsonb, 'Stuff with grated carrots, spinach, and paneer for a complete macro profile. Use ½ tsp oil per cheela.', 'approved', NOW())
ON CONFLICT (lower(name)) DO NOTHING;
